/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppJourneyRouteImport } from './routes/_app.journey'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReadingRouteImport } from './routes/_app.reading'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingRoute = AppReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journey': typeof AppJourneyRoute
  '/profile': typeof AppProfileRoute
  '/reading': typeof AppReadingRoute
  '/sign-in/$': typeof SignInSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof AppJourneyRoute
  '/profile': typeof AppProfileRoute
  '/reading': typeof AppReadingRoute
  '/sign-in/$': typeof SignInSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/journey': typeof AppJourneyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reading': typeof AppReadingRoute
  '/sign-in/$': typeof SignInSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/journey' | '/profile' | '/reading' | '/sign-in/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journey' | '/profile' | '/reading' | '/sign-in/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/journey'
    | '/_app/profile'
    | '/_app/reading'
    | '/sign-in/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/journey': {
      id: '/_app/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading': {
      id: '/_app/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AppReadingRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppJourneyRoute: typeof AppJourneyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReadingRoute: typeof AppReadingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJourneyRoute: AppJourneyRoute,
  AppProfileRoute: AppProfileRoute,
  AppReadingRoute: AppReadingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
